REM filename: STERM
REM Simplest possible BBC serial terminal program
:
ON ERROR OSCLI "FX2":OSCLI "FX3":REPORT:PRINT:END
*FX229,1
*FX2,2
REPEAT
IF ADVAL(-1):OSCLI "FX3,3":VDU GET:*FX3
IF ADVAL(-2):OSCLI "FX2,1":VDU GET:*FX2,2
UNTIL FALSE