REM filename: basm
DIM asmOSWRCH 16
OSWRCH=&FFEE
char%=&70
PROCasmInit
A%=FNcallOSWRCH(ASC("M"))
IF A%<>1 THEN PRINT "ERROR CALLING OSWRCH"
A%=FNcallOSWRCH(ASC("F"))
IF A%<>1 THEN PRINT "ERROR CALLING OSWRCH"
END

DEF PROCasmInit
FOR I%=0 TO 2 STEP 2:P%=asmOSWRCH
  [OPT I%
   LDA &70
   JSR OSWRCH
   LDA #&01
   LDX #&02
   LDY #&03
   RTS
  ]
NEXT I%
ENDPROC

DEF FNcallOSWRCH(c)
?&70=c
R%=USR(asmOSWRCH)
=(R% AND &FF)
