#!/usr/bin/env bash
# Build FN-BOOT.ssd: the boot disk. Each transient utility is a
# standalone RAM binary that calls the resident ROM through the stable utility
# ABI table (role-split Lever B disk execution).
#
# Mechanism: build the product ROM, generate a ca65 source (rom_abi.s)
# that maps resident routine imports to fixed jump-table slots and direct data
# imports to the target machine's stable workspace addresses, then assemble each
# utility (+ duplicated utils-internal helpers + a generated entry wrapper) for
# RAM and link it against rom_abi.o. See docs/ROM_ROLE_SPLIT_PHASE4.md /
# docs/ROM_ROLE_SPLIT_PHASE5.md.
#
# Filename note: when a transient command is typed, fn-rom leaves service &04
# unclaimed and the MOS asks the FS to *RUN it as a file. The FS reads the leaf
# from the *start* of the command line (read_fspba in fs_functions.s rewinds to
# offset 0), so the requested leaf is the **full typed name** including any
# leading F (e.g. *FDRIVE -> "FDRIVE", *FORM -> "FORM", *COPY -> "COPY"). DFS
# caps a disc at 31 files and a leaf at 7 chars; every transient command name is
# <= 7 chars (the unmount command is *FUMOUNT, not *FUNMOUNT, for this reason).
set -euo pipefail
cd "$(dirname "$0")/.."          # repos/fn-rom
root="$(pwd)"

MACHINE="${BUILD_MACHINE:-BBC}"
OUT="$root/build/fn-boot"        # intermediate objects
STAGE="$root/build/fn-boot-ssd"  # only the files that go on the disk
ABISRC="$OUT/rom_abi.s"
UTILCFG="$OUT/fn-util.cfg"
SSD="${FN_BOOT_SSD:-$root/build/FN-BOOT.ssd}"

case "$MACHINE" in
  BBC)
    ROM_BASENAME="fujinet.rom"
    UTIL_LOAD_ADDR="${FN_UTIL_LOAD_ADDR:-0x1900}"
    ;;
  MASTER)
    ROM_BASENAME="fujinet-master.rom"
    UTIL_LOAD_ADDR="${FN_UTIL_LOAD_ADDR:-0x0E00}"
    ;;
  *)
    echo "Invalid BUILD_MACHINE: $MACHINE (expected BBC or MASTER)" >&2
    exit 1
    ;;
esac
LBL="$root/build/$ROM_BASENAME.lbl"
UTIL_ABI_SRC="$root/src/kernel/util_abi.s"

# cc65 defines that must match the ROM build the binaries call into.
ASDEF=(-D "FUJINET_MACHINE_$MACHINE" -D FUJINET_INTERFACE_SERIAL -D FN_UTIL_BINARY)
[ "$MACHINE" = "MASTER" ] && CPU=(--cpu 65C02) || CPU=()
INC=(-I "$root/src" -I "$root/src/inc")

rm -rf "$OUT" "$STAGE"; mkdir -p "$OUT" "$STAGE"

UTIL_LOAD_HEX="$(python3 - "$UTIL_LOAD_ADDR" <<'PY'
import sys
value = sys.argv[1].strip()
if value.startswith("&"):
    value = "0x" + value[1:]
addr = int(value, 0)
if not 0 <= addr <= 0xFFFF:
    raise SystemExit(f"invalid FN utility load address: {sys.argv[1]}")
print(f"{addr:04X}")
PY
)"
UTIL_INF_ADDR="$(printf '00%s' "$UTIL_LOAD_HEX")"
UTIL_RAM_SIZE="$(python3 - "$UTIL_LOAD_HEX" <<'PY'
import sys
addr = int(sys.argv[1], 16)
size = 0x8000 - addr
if size <= 0:
    raise SystemExit("FN utility load address must be below $8000")
print(f"{size:04X}")
PY
)"
cat > "$UTILCFG" <<EOF
# Generated by scripts/build_fn_boot.sh for BUILD_MACHINE=$MACHINE.
MEMORY {
    ZP:  file = "", start = \$0000, size = \$0100, type = rw;
    RAM: file = %O, start = \$$UTIL_LOAD_HEX, size = \$$UTIL_RAM_SIZE, fill = no;
}
SEGMENTS {
    ZEROPAGE: load = ZP,  type = zp,  optional = yes;
    CODE:     load = RAM, type = ro;
    RODATA:   load = RAM, type = ro,  optional = yes;
    RO_EARLY: load = RAM, type = ro,  optional = yes;
    HEADER:   load = RAM, type = ro,  optional = yes;
    DATA:     load = RAM, type = rw,  optional = yes;
    BSS:      load = RAM, type = bss, optional = yes;
}
EOF
echo "==> transient utility load/exec address: $UTIL_INF_ADDR"

echo "==> building product ROM (for resident symbol addresses)"
make -B -C "$root" BUILD_MACHINE="$MACHINE" all >/dev/null

echo "==> generating rom_abi.s from $LBL"
python3 - "$LBL" "$ABISRC" "$UTIL_ABI_SRC" <<'PY'
import re, sys
lbl, out, abi_src = sys.argv[1], sys.argv[2], sys.argv[3]
abi_routines = []
for line in open(abi_src):
    m = re.match(r'^fuji_util_abi_([A-Za-z_][A-Za-z0-9_]*):\s*$', line.strip())
    if m and m.group(1) not in ("start", "end", "signature"):
        abi_routines.append(m.group(1))
if not abi_routines:
    raise SystemExit(f"no ABI slots found in {abi_src}")
abi_addr = {name: 0x8030 + (i * 3) for i, name in enumerate(abi_routines)}
zp, ab = [], []
for line in open(lbl):
    m = re.match(r'^al\s+([0-9A-Fa-f]{6})\s+\.([A-Za-z_][A-Za-z0-9_]*)\s*$', line.strip())
    if not m:
        continue
    addr = int(m.group(1), 16) & 0xFFFF
    name = m.group(2)
    if name in abi_addr:
        addr = abi_addr[name]
    (zp if addr < 0x100 else ab).append((name, addr))
with open(out, "w") as f:
    f.write("; Generated for FN-BOOT transient utility linkage.\n")
    f.write("; Resident routine imports point at the stable ROM utility ABI table.\n")
    for name, addr in zp:
        f.write(f".exportzp {name}\n{name} = ${addr:04X}\n")
    for name, addr in ab:
        f.write(f".export {name}\n{name} = ${addr:04X}\n")
print(f"   {len(zp)} zp + {len(ab)} abs symbols ({len(abi_addr)} ABI routine slots)")
PY

# Assemble the shared resident-ABI object once.
ca65 "${CPU[@]}" "${ASDEF[@]}" "${INC[@]}" "$ABISRC" -o "$OUT/rom_abi.o"

gen_rom_select_code() {
  cat <<'EOF'

ROMSEL_CURRENT  = $00F4
ROMSEL          = $FE30
OSWRCH          = $FFEE

select_fujinet_rom:
        lda     ROMSEL_CURRENT
        pha
        ldx     #$0F
@slot_loop:
        stx     ROMSEL_CURRENT
        stx     ROMSEL
        jsr     check_current_fujinet_rom
        bcc     @found
        dex
        bpl     @slot_loop
        pla
        sta     ROMSEL_CURRENT
        sta     ROMSEL
        sec
        rts
@found:
        pla
        clc
        rts

check_current_fujinet_rom:
        lda     $8000
        bne     @no
        lda     $8001
        bne     @no
        lda     $8002
        bne     @no
        lda     $8003
        cmp     #$4C
        bne     @no
        lda     $8006
        cmp     #$82
        bne     @no
        ldy     #$00
@title_loop:
        lda     fujinet_rom_title,y
        beq     @title_ok
        cmp     $8009,y
        bne     @no
        iny
        bne     @title_loop
@title_ok:
        ldy     #$00
@sig_loop:
        lda     fujinet_abi_signature,y
        beq     @yes
        cmp     fuji_util_abi_signature,y
        bne     @no
        iny
        bne     @sig_loop
@yes:
        clc
        rts
@no:
        sec
        rts

print_missing_rom:
        ldy     #$00
@msg_loop:
        lda     missing_rom_msg,y
        beq     @done
        jsr     OSWRCH
        iny
        bne     @msg_loop
@done:
        rts

fujinet_rom_title:
        .byte   "FujiNet", 0
fujinet_abi_signature:
        .byte   "FNABI1", 0
missing_rom_msg:
        .byte   "FujiNet ROM ABI not found", $0D, 0
EOF
}

# Generate a tiny entry wrapper for one handler, then enter the resident handler;
# its closing rts returns to the MOS (the binary is entered by jmp, tail-call
# style). The GSINIT string pointer (text_pointer) must point at the command's
# argument tail before the handler parses it. Two modes:
#   args : the FS *RUN leaves the tail addressed by fuji_text_ptr_hi:offset, so
#          point text_pointer there (commands that take parameters).
#   noarg: point text_pointer at an in-binary CR, i.e. an empty parameter line
#          (commands that take none — the *RUN handoff is not relied upon).
gen_wrapper() {
  local handler="$1" mode="$2" out="$OUT/wrap_${handler}.s"
  if [ "$mode" = noarg ]; then
    cat > "$out" <<EOF
        .export   _util_start
        .importzp text_pointer
        .import   $handler
        .import   fuji_util_abi_signature
        .segment "CODE"
_util_start:
        jsr     select_fujinet_rom
        bcc     @rom_ok
        jsr     print_missing_rom
        rts
@rom_ok:
        lda     #<empty_line
        sta     text_pointer
        lda     #>empty_line
        sta     text_pointer+1
        ldy     #\$00
        jmp     $handler
empty_line:
        .byte   \$0D
        $(gen_rom_select_code)
EOF
  else
    cat > "$out" <<EOF
        .export   _util_start
        .importzp text_pointer
        .import   $handler
        .import   fuji_util_abi_signature
        .import   fuji_text_ptr_hi
        .import   fuji_text_ptr_offset
        .segment "CODE"
_util_start:
        jsr     select_fujinet_rom
        bcc     @rom_ok
        jsr     print_missing_rom
        rts
@rom_ok:
        lda     fuji_text_ptr_offset
        sta     text_pointer
        lda     fuji_text_ptr_hi
        sta     text_pointer+1
        ldy     #\$00
        jmp     $handler
        $(gen_rom_select_code)
EOF
  fi
  echo "$out"
}

# build_util LEAF HANDLER SRC...  (SRC = the command module + any utils-internal
# helpers it depends on; the wrapper is generated and linked first so _util_start
# is the binary's entry at PAGE). Prefix HANDLER with "noarg:" for a no-parameter
# command (uses the in-binary empty parameter line).
build_util() {
  local leaf="$1" handler="$2"; shift 2
  local mode=args
  case "$handler" in noarg:*) mode=noarg; handler="${handler#noarg:}";; esac
  local wrap; wrap="$(gen_wrapper "$handler" "$mode")"
  local objs=("$OUT/rom_abi.o")
  echo "==> $leaf  ($handler)"
  for src in "$wrap" "$@"; do
    local o="$OUT/$(basename "${src%.s}").$leaf.o"
    ca65 "${CPU[@]}" "${ASDEF[@]}" "${INC[@]}" "$src" -o "$o"
    objs+=("$o")
  done
  ld65 -C "$UTILCFG" -o "$STAGE/$leaf" "${objs[@]}"
  printf '%s %s %s\n' "$leaf" "$UTIL_INF_ADDR" "$UTIL_INF_ADDR" > "$STAGE/$leaf.inf"
}

U="$root/src/utils"

# Each binary is staged under the full command name the FS *RUN looks up.
build_util FDRIVE  noarg:cmd_fs_fdrive "$U/cmd_fdrive.s" "$U/cmd_flist.s" "$U/flist_resolve_target.s"
build_util FCD     cmd_fs_fcd      "$U/cmd_fcd.s" "$U/flist_resolve_target.s"
build_util FLS     cmd_fs_flist    "$U/cmd_flist.s" "$U/flist_resolve_target.s"
build_util FLIST   cmd_fs_flist    "$U/cmd_flist.s" "$U/flist_resolve_target.s"
build_util FNEW    cmd_fs_fnew     "$U/cmd_fs_fnew.s"
build_util FOUT    cmd_fs_fout     "$U/cmd_fout.s"
build_util FUMOUNT cmd_fs_funmount "$U/cmd_funmount.s"   # *FUMOUNT (renamed from FUNMOUNT to fit DFS 7-char leaf)
build_util COPY    cmd_fs_copy     "$U/cmd_copy.s"
build_util DESTROY cmd_fs_destroy  "$U/cmd_destroy.s" "$U/confirm.s"
build_util WIPE    cmd_fs_wipe     "$U/cmd_wipe.s" "$U/confirm.s"
build_util TITLE   cmd_fs_title    "$U/cmd_title.s"
build_util ACCESS  cmd_fs_access   "$U/cmd_access.s"
build_util RENAME  cmd_fs_rename   "$U/cmd_rename.s"
build_util VERIFY  cmd_fs_verify   "$U/cmd_verify_format.s"
build_util MAP     cmd_fs_map      "$U/cmd_free_map.s"
build_util FORM    cmd_fs_form     "$U/cmd_verify_format.s"
build_util FREE    cmd_fs_free     "$U/cmd_free_map.s"

echo "==> staging + bundling FN-BOOT.ssd ($(ls "$STAGE" | grep -vc '\.inf$') files)"
# Keep the source !BOOT editable as normal text, but store BBC command input
# lines with CR-only terminators. LF moves the BBC cursor down without returning
# to column 0, which corrupts *EXEC/!BOOT command entry.
tr '\n' '\r' < "$root/boot-bin/!BOOT" > "$STAGE/!BOOT"
printf '$.!BOOT 000000 000000\n' > "$STAGE/!BOOT.inf"
if [ -n "${FN_BOOT_EXTRA_STAGE:-}" ]; then
  if [ ! -d "$FN_BOOT_EXTRA_STAGE" ]; then
    echo "FN_BOOT_EXTRA_STAGE is not a directory: $FN_BOOT_EXTRA_STAGE" >&2
    exit 1
  fi
  echo "==> staging extra utility files from $FN_BOOT_EXTRA_STAGE"
  cp -R "$FN_BOOT_EXTRA_STAGE"/. "$STAGE"/
fi
"$root/scripts/create_ssd.py" -i "$STAGE" -o "$SSD" -t FN-BOOT
echo "==> $SSD"
