#!/usr/bin/env python3
from __future__ import annotations

import os
import sys
from pathlib import Path
from math import isqrt


# The shapes come from the bounce-world server project (Kotlin), given as the
# first argument or BOUNCE_WORLD_SERVER. (The workspace's BOUNCE_WORLD is the
# client repo, not this.)
SHAPES_SUBDIR = Path("server/src/jvmMain/resources/shapes")

SHAPE_FILES = [
    "shape01.dat",
    "shape02.dat",
    "shape03.dat",
    "shape04.dat",
    "shape05.dat",
    "shape06.dat",
    "shape07.dat",
    "shape10.dat",
    "shape11.dat",
    "shape12.dat",
    "shape14.dat",
    "shape15.dat",
    "shape18.dat",
    "shape19.dat",
    "shape20.dat",
    "shape21.dat",
    "shape22.dat",
    "shape23.dat",
    "shape24.dat",
]


BBC_MAP = {
    "┌": "+",
    "┐": "+",
    "└": "+",
    "┘": "+",
    "┤": "+",
    "├": "+",
    "┬": "+",
    "┴": "+",
    "┼": "+",
    "─": "-",
    "│": "|",
    "▌": "#",
    "▐": "#",
    "▄": "#",
    "▀": "#",
    "▖": ".",
    "▗": ".",
    "▘": ".",
    "▝": ".",
    "▜": "#",
    "▛": "#",
    "▟": "#",
    "▙": "#",
    "█": "#",
}


def to_bbc_chars(text: str) -> str:
    return "".join(BBC_MAP.get(ch, ch) for ch in text)


def shapes_dir() -> Path:
    root = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("BOUNCE_WORLD_SERVER")
    if not root:
        sys.exit("usage: generate_bbc_shapes.py BOUNCE_WORLD_CHECKOUT (or set BOUNCE_WORLD_SERVER)")
    path = Path(root) / SHAPES_SUBDIR
    if not path.is_dir():
        sys.exit(f"no shapes directory at {path}")
    return path


def read_shape(shapes: Path, shape_id: int, name: str) -> tuple[int, int, str]:
    path = shapes / name
    lines = path.read_text(encoding="utf-8").splitlines()
    shape_text = "".join(lines[1:])
    width = isqrt(len(shape_text))
    if width * width != len(shape_text):
        raise ValueError(f"{name}: invalid square size")
    return shape_id, width, to_bbc_chars(shape_text)


def bbc_string_literal(text: str) -> str:
    return '"' + text.replace('"', "'") + '"'


def main() -> None:
    source = shapes_dir()
    shapes = [read_shape(source, i, name) for i, name in enumerate(SHAPE_FILES)]
    total_payload = 0

    print("REM Generated by tools/generate_bbc_shapes.py")
    print(f"shapeCount%={len(shapes)}")
    for shape_id, width, payload in shapes:
        print(f"DATA {shape_id},{width},{len(payload)},{bbc_string_literal(payload)}")
        total_payload += len(payload)

    print(f"REM total size: {total_payload}")

if __name__ == "__main__":
    main()
