; in case we extend this to different devices
MACRO DEVICE_NAME
    EQUS " Normal"
ENDMACRO

MACRO BOOT_NAME
    BASE_NAME
    DEVICE_NAME
    EQUB 13, 13
ENDMACRO

MACRO BUILD_NAME
    BASE_NAME
    DEVICE_NAME
    EQUB 0
ENDMACRO

MACRO BUILD_COPYRIGHT
    EQUS "(C)2024 Mark Fisher", 0
ENDMACRO

MACRO BUILD_VERSION
    EQUS "0.0.1", 0     ; #VERSION#
ENDMACRO
